# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyllableSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FilePathField()),
                ('sound', models.CharField(max_length=10)),
                ('tone', models.IntegerField()),
                ('display', models.CharField(max_length=10)),
            ],
        ),
    ]
