# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 00:24
from __future__ import unicode_literals
from django.db import migrations
from django.core.management import call_command
import os

fixture = 'initial_data.json'

def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label='syllable_samples')

def unload_fixture(apps, schema_editor):
    SyllableSample = apps.get_model("syllable_sample", "SyllableSample")
    SyllableSample.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('syllable_samples', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture),
    ]
